### ISSUE TITLE
Can't deploy because of undefined local variable or method `revision

### ISSUE THREAD

**Issue by Kyrremann** [seattlerb/vlad#58]
This looks like a similar problem that #40, but I'm running at latest version after just updating.

```
$ rake vlad:deploy
rake aborted!
NameError: undefined local variable or method `revision' for main:Object
/home/kyreri/.rvm/gems/ruby-1.9.3-p551/gems/vlad-2.6.5/lib/vlad/core.rb:82:in `block (2 levels) in <top (required)>'
/home/kyreri/.rvm/gems/ruby-1.9.3-p551/gems/rake-remote_task-2.3.0/lib/rake/remote_task.rb:689:in `call'
/home/kyreri/.rvm/gems/ruby-1.9.3-p551/gems/rake-remote_task-2.3.0/lib/rake/remote_task.rb:689:in `block (2 levels) in execute'
Tasks: TOP => vlad:update_app
(See full trace by running task with --trace)

```

With --trace
```
$ rake vlad:deploy --trace
** Invoke vlad:deploy (first_time)
** Invoke vlad:update (first_time)
** Execute vlad:update
** Invoke vlad:update_app (first_time)
** Execute vlad:update_app
ssh user@server 'rm -rf /home/github-jira-integration/releases/20151119154602'
rake aborted!
NameError: undefined local variable or method `revision' for main:Object
/home/kyreri/.rvm/gems/ruby-1.9.3-p551/gems/vlad-2.6.5/lib/vlad/core.rb:82:in `block (2 levels) in <top (required)>'
/home/kyreri/.rvm/gems/ruby-1.9.3-p551/gems/rake-remote_task-2.3.0/lib/rake/remote_task.rb:689:in `call'
/home/kyreri/.rvm/gems/ruby-1.9.3-p551/gems/rake-remote_task-2.3.0/lib/rake/remote_task.rb:689:in `block (2 levels) in execute'
Tasks: TOP => vlad:update_app
```

Bundle:
```
$ bundle
Using rake 10.4.2
Using backports 3.6.7
Using daemons 1.2.3
Using diff-lcs 1.2.5
Using eventmachine 1.0.8
Using multi_json 1.11.2
Using open4 1.3.4
Using rack 1.6.4
Using rack-protection 1.5.3
Using rack-test 0.6.3
Using rake-remote_task 2.3.0
Using rspec-support 3.4.0
Using rspec-core 3.4.1
Using rspec-expectations 3.4.0
Using rspec-mocks 3.4.0
Using rspec 3.4.0
Using tilt 2.0.1
Using sinatra 1.4.6
Using sinatra-contrib 1.4.6
Using thin 1.6.4
Using vlad 2.6.5
Using vlad-git 2.2.0
Using bundler 1.7.6
```

**Comment by zenspider** [comment]
I'm not sure yet, but it looks like vlad-git needs to be updated. rake-remote_task updated here:

=== 2.2.1 / 2013-03-18

* 1 minor enhancement:

  * Pushed revision (head) variable down to vlad. (jari-dk)

and it looks like vlad-git hasn't updated: https://github.com/jbarnette/vlad-git/blob/master/CHANGELOG.rdoc

Lemme know if that seems right or wrong. Probably need to file a ticket there. I can help push if you need it.

**Comment by Kyrremann** [comment]
Thanks for the quick response. I didn't quiet understand what you meant, but by reading the `vlad-git` documents I tried with `set :revision, "master"` in my `config/deploy.rb` and that solved it. So I'm guessing that `vlad-git` doesn't properly default to `master`, as stated in the documents.

But, now I'm stuck at https://github.com/jbarnette/vlad-git/issues/7 where it won't deploy new versions. So need to work out that.

**Comment by zenspider** [comment]
Please close if your issue is addressed. Feel free to send me a PR with an FAQ entry or something added.
